### ISSUE TITLE
MAX_TOKENS in error

### ISSUE THREAD

**Issue by rostalsan** [Zuellni/ComfyUI-ExLlama-Nodes#1]
hello,nice work.but when I load the example workflow it come out:

_________________________________________
* ZuellniExLlamaGenerator 5:
  - Required input is missing: max_tokens
Output will be ignored
Failed to validate prompt for output 11:
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': 'Required input is missing: max_tokens', 'extra_info': {}}

_________________________________________

it seems MAX_TOKENS isn't set ，would you please check?

**Comment by Zuellni** [comment]
I forgot to update the workflow after renaming some fields, the new one shouldn't have any errors.
