### ISSUE TITLE
Load llm into free vram on multiple gpus

### ISSUE THREAD

**Issue by xandix1939** [Zuellni/ComfyUI-ExLlama-Nodes#10]
Can you add the auto_split function from exllama2 into your nodes?

So it will distribute over multiple gpus vram.

Thank you.

**Comment by Zuellni** [comment]
Sorry for the delay, as far as I can tell auto_split is the default behavior when nothing is specified but I added an explicit gpu_split field. It should function the same way it does in exllama, eg. `8192, 4096` will allocate 8gb to the first device and 4gb to the second one. I don't have multiple gpus to test so let me know if it works.

**Comment by Zuellni** [comment]
It seems like auto_split was using a different loading method, but I added it now. Should work by specifying `auto` in `gpu_split`.

**Comment by xandix1939** [comment]
Thanks for your update, but now the node does not work anymore when updating exllamav2. theres a torch error.

**Comment by xandix1939** [comment]
Thank you, works again. You did a great job with this node as i use it very often.
