### ISSUE TITLE
language model install

### ISSUE THREAD

**Issue by mylesgoose** [Zuellni/ComfyUI-ExLlama-Nodes#11]
Hello. 
I Installed this node to ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes-main 
and then I installed the requirements txt files. everything went smoothly. then I copied over your png image from your readme and it loaded up perfectly. however there are two things missing. the loader for the language model is not actually a loader it is a txt field that you have typed zephyr-7b-beta-5.0bpw-h6-exl2  I can see that model on hugging face https://huggingface.co/LoneStriker/zephyr-7b-beta-5.0bpw-h6-exl2 however I am unsure how to load the model. or if i download the model where do i put it? in what folder? is this thing automatically searching the hugging face cache? if i want to load a new model say llama 70b how do I do so. into what folder do I put the model itself.

Thanks

**Comment by GentlemanHu** [comment]
put it anywhere, then copy absolute path to model_dir 
<img width="396" alt="image" src="https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/34559079/85feb7d5-b7dd-4a3e-ae1d-5b6b6b2b8cef">


eg.
```shell
/content/drive/colab_ai/ComfyUI/custom_nodes/ComfyUI-ExLlama-Nodes/zephyr-7b-beta-5.0bpw-h6-exl2
```

**Comment by Zuellni** [comment]
There is no automatic downloading, I don't really want to complicate everything too much. The `model_dir` field simply checks whatever relative (to the comfy root) or absolute path you provide.

If you want to download a model from huggingface, the easiest way is to git clone the whole repo like so:
```
git clone https://huggingface.co/TheBloke/zephyr-7B-beta-GPTQ -b gptq-4bit-32g-actorder_True zephyr-7b-gptq-g32
```
Then you can point the loader to the downloaded repo, eg. `D:\Models\zephyr-7b-gptq-g32`

**Comment by Zuellni** [comment]
I changed the loader so you don't have to provide model paths manually anymore. Just put downloaded models (whole repos) in `<root_comfyui_dir>/models/llm/` or add `llm: <some_dir>` to `extra_model_paths.yaml`.

![03](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/123005779/eb7b9e83-1e5a-4a5e-90ec-fdc2a10907ff)
