### ISSUE TITLE
Any plans to add more detailed instructions for using the nodes? Specifically the Replace node?

### ISSUE THREAD

**Issue by tro2789** [Zuellni/ComfyUI-ExLlama-Nodes#13]
Hi, I'm starting to test these nodes in a workflow, but I can't seem to grasp how the Replace node is supposed to work. I'm also unsure exactly where my initial prompt is supposed to go. 

I see the Generator node's text field, and how it's being used to instruct the LLM on how to behave and receive the appropriate response. When I try to define a variable like [a] in that text field, it doesn't seem to work as intended. Perhaps I'm just not understanding the default workflow you've provided. Are you able to clarify things such as:

1. Where the user is supposed to put their initial prompt.
2. The purpose of the Replace node, with an example of it being used to affect image generation.

That would be immensely helpful. My ultimate goal is to include LLM prompt enrichment in my workflow in order to create better images. Thanks!

Trevor

**Comment by Zuellni** [comment]
Sorry, for some reason I didn't see your issue or get any notifications, not sure if going blind or a problem with GitHub.

In any case, the `Replacer` node is just there so you can combine text more easily, it takes in strings as input and converts any variable names it finds in the `text` field to their values, outputting a string as well. It's not strictly necessary for anything, and there are probably other nodes that use regex or something, might want to use those instead, depending on use case.

The prompt/instruction generally goes into the `text` field of the `Generator` node, it's just a string too so you can use it with other nodes.

For a simple example of how the `Replacer` node can be used, look at this:
![workflow](https://github.com/user-attachments/assets/2c954d37-dfd8-49a9-bf59-126355932e3a)

The text in red is the raw model output, I inserted it between some tags with `Replacer`. Green is the combined output that is then passed to `CLIPTextEncode`. Hope this helps.
