### ISSUE TITLE
Model undefined not found?

### ISSUE THREAD

**Issue by metamountain** [Zuellni/ComfyUI-ExLlama-Nodes#15]
Sorry I  put the model to the right directory, but it still isnt found. 

E:\ComfyUI_windows_portable\ComfyUI\models\llm\mistral-7b-exl2-b5

The model is not renamed .  Its called output.safetensors
What am i missing ?

THX in Advance....  

Metamountain

**Comment by Zuellni** [comment]
Do you mean you're not seeing the model listed in the loader node? Do you have a `config.json` and other files in the `mistral-7b-exl2-b5` folder, next to `output.safetensors`? If you're not using git to clone the model repo you should download all the files in it manually and place them in the same folder.

**Comment by metamountain** [comment]
No, All done correctly i  had hoped....
![cshot](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/129164666/7fe1b1ea-aa33-45de-abef-fd7491f3f5ef)

**Comment by metamountain** [comment]
![grafik](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/129164666/a564db1b-2e85-4541-9422-b7b72e0cfb8e)

**Comment by Zuellni** [comment]
That seems correct except there shouldn't be anything in the `gpu_split` field if you're not using that. Make sure your nodes are up to date, then remove and add the loader node again.

**Comment by metamountain** [comment]
Thx for you immidiate help. Unfortunately still not working, even after reinstalling from scratch...

**Comment by Zuellni** [comment]
That's quite strange, looking at the screenshot above I'm pretty sure your nodes were just outdated. I assume there are no errors in the console? If you're using the manager to install nodes try cloning the repo manually instead. Also did you try opening the example workflow from the readme?

**Comment by metamountain** [comment]
Sure !
![grafik](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/129164666/ff809882-d162-4f62-9e09-e1b28befcfba)

**Comment by metamountain** [comment]
Yuuhuu!!!!!!!!!!  You save me. Had to delete the custom_node and install it manually. there was another llama node i also deleted...

Thank you very much !
