### ISSUE TITLE
I get this ominous error when trying to execute

### ISSUE THREAD

**Issue by worthy7** [Zuellni/ComfyUI-ExLlama-Nodes#18]
![image](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/4762399/b1fe426a-7a62-4fcb-a244-63039006b9eb)

**Comment by Zuellni** [comment]
Some more info about your setup? Python/Torch/ExllamaV2 versions? Did you install a wheel or compile yourself? Portable ComfyUI or not? What's in the model folder?

**Comment by worthy7** [comment]
Windows
Python 310
torch                     2.3.0+cu121
exllamav2                 0.0.20+cu12

Installed a wheel
pip install https://github.com/turboderp/exllamav2/releases/download/v0.0.20/exllamav2-0.0.20+cu121-cp310-cp310-win_amd64.whl 

Loads fine according to comfyui.

It is nested, as the readme says to clone in the models/llm folder.
Anyway I just made it the same structure as you said, so but I get the same error. Usually nested models are not an issue in comfy, I nest all my checkpoints in different folders depending on what they are for (1.5, turbo etc)

![image](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/4762399/cc288c0d-943c-4460-ac60-df36d19c8ebd)

**Comment by worthy7** [comment]
Sorry I totally forgot to just _check the damn console_ when this message appeared, it has more info, some kind of "Memory error"?

![image](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/4762399/0071c1f5-fcab-467c-9c93-0915ff2b47e9)

**Comment by Zuellni** [comment]
Looking at your model folder, your `output.safetensors` file is only 1 KB while it should be around 6 GB, meaning the model wasn't downloaded correctly. Make sure your `git` is up to date and that you have `lfs` enabled, and that the download wasn't interrupted.

Try cloning again with:
```
git lfs clone https://huggingface.co/turboderp/Llama-3-8B-Instruct-exl2 -b 6.0bpw models/llm/Llama-3-8B-Instruct-exl2-6.0bpw
```

Also, make sure your card has enough VRAM to load this model, 6bpw with 8192 context and FP16 cache requires about 8 GB, 2048 context with Q4 cache ~ 6 GB. You can get lower bpw quants on HF if that isn't the case.

**Comment by worthy7** [comment]
VRam isn't a problem but you're right about LFS! Mabye change that command in the readme? I am not a newbie to git but I just blindly expect readme's to work. Thanks!
Downloading now....

**Comment by Zuellni** [comment]
It is my understanding `git lfs clone` has been deprecated for a while and `git clone` downloads lfs objects by default now so this should be some configuration difference on your side.

**Comment by worthy7** [comment]
I see, so perhaps I disabled it some time in the past.
It worked great, thanks so much!
