### ISSUE TITLE
name 'exllamav2_ext' is not defined

### ISSUE THREAD

**Issue by xueqing0622** [Zuellni/ComfyUI-ExLlama-Nodes#19]
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\__init__.py", line 1, in <module>
    from . import exllama, text
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\exllama.py", line 6, in <module>
    from exllamav2 import *
  File "F:\ComfyUI\python_embeded\Lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "F:\ComfyUI\python_embeded\Lib\site-packages\exllamav2\model.py", line 31, in <module>
    from exllamav2.config import ExLlamaV2Config
  File "F:\ComfyUI\python_embeded\Lib\site-packages\exllamav2\config.py", line 5, in <module>
    from exllamav2.fasttensors import STFile
  File "F:\ComfyUI\python_embeded\Lib\site-packages\exllamav2\fasttensors.py", line 6, in <module>
    from exllamav2.ext import exllamav2_ext as ext_c
  File "F:\ComfyUI\python_embeded\Lib\site-packages\exllamav2\ext.py", line 281, in <module>
    ext_c = exllamav2_ext
            ^^^^^^^^^^^^^
NameError: name 'exllamav2_ext' is not defined

**Comment by xueqing0622** [comment]
already install by in python env.
python.exe -m pip install exllamav2-0.1.5+cu118.torch2.2.0-cp311-cp311-win_amd64.whl

**Comment by Zuellni** [comment]
I haven't checked if there are any compatibility issues with the newest version of exllamav2 yet but does executing `python -c "import exllamav2"` in the same env also display that error? If so you probably installed the wrong wheel.

**Comment by cielglan** [comment]
I have the same issue.. I tried everything what I can do, but I can not solve this problem. Any idea ?

**Comment by Zuellni** [comment]
Please provide more info, I can't really do anything otherwise. What is your platform, python version, torch version, (torch) cuda version, how are you installing exllamav2 (jit? wheel? which wheel?), etc.

**Comment by herrygoon** [comment]
I have the same issue..
os: windows10 22H2,Python:3.11.8, torch version:2.2.1+cu121
NVIDIA-SMI 555.85  Driver Version: 555.85   CUDA Version: 12.5 
install by whl
python -m pip install exllamav2-0.1.7+cu121.torch2.3.1-cp311-cp311-win_amd64.whl
python -m pip install "flash_attn-2.6.1+cu123torch2.2.2cxx11abiFALSE-cp311-cp311-win_amd64.whl"

**Comment by Zuellni** [comment]
Try the wheel for torch 2.2: [exllamav2-0.1.7+cu121.torch2.2.0-cp311-cp311-win_amd64.whl](https://github.com/turboderp/exllamav2/releases/download/v0.1.7/exllamav2-0.1.7+cu121.torch2.2.0-cp311-cp311-win_amd64.whl)

**Comment by paul0728** [comment]
> Try the wheel for torch 2.2: [exllamav2-0.1.7+cu121.torch2.2.0-cp311-cp311-win_amd64.whl](https://github.com/turboderp/exllamav2/releases/download/v0.1.7/exllamav2-0.1.7+cu121.torch2.2.0-cp311-cp311-win_amd64.whl)

Error still.
![image](https://github.com/user-attachments/assets/190d6f0d-c764-41ea-a635-61dbd3935d79)
