### ISSUE TITLE
Which folder is the downloaded model in?

### ISSUE THREAD

**Issue by Mocha-s** [Zuellni/ComfyUI-ExLlama-Nodes#2]
![Snipaste_2023-09-18_21-03-24](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/20685520/16d1533b-db76-4763-baf3-a82846efbac3)
The confirmation of the model file is placed in the folder corresponding to the path.

**Comment by Zuellni** [comment]
You have to specify the full path, eg `D:\Models\Something-7B` or `./home/models/Something-Else-13b`.

**Comment by Mocha-s** [comment]
How can I specify a folder directory? Sorry, I'm not a professional programmer. I can't even find one in the plug-in directory to configure the model path config.json, screenshot before I tried to specify it to go to still and a folder. But as a result, the model file can not be found.
![Snipaste_2023-09-18_22-03-27](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/20685520/c2ece9f0-0e00-4b47-ac2b-24e1935e2934)
![Snipaste_2023-09-18_22-04-20](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/20685520/e5e24c81-bc61-453a-ab87-a0b771c995c6)

**Comment by Zuellni** [comment]
Assuming you're trying to load [this model](https://huggingface.co/TheBloke/MythoLogic-Mini-7B-GPTQ), you can either `git clone https://huggingface.co/TheBloke/MythoLogic-Mini-7B-GPTQ`, or you can download all the required files manually and place them in some empty folder, and then point to it in `model_dir`. By required files I mean:
```
added_tokens.json
config.json
generation_config.json
model.safetensors
quantize_config.json
special_tokens_map.json
tokenizer.json
tokenizer.model
tokenizer_config.json
```
`model.safetensors` by itself is not enough.

**Comment by Mocha-s** [comment]
Thanks for answering the questions and solving the problem according to your tips. The author is advised to put this process in the introduction

**Comment by Zuellni** [comment]
There's already plenty of better guides on this than anything I can come up with but I added a note to the readme.
