### ISSUE TITLE
How to use PyTorch version 2.2.2+cu121？

### ISSUE THREAD

**Issue by bluesEnao** [Zuellni/ComfyUI-ExLlama-Nodes#26]
-log

Cannot import E:\CT\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes module for custom nodes: name 'exllamav2_ext' is not defined
### Loading: ComfyUI-Impact-Pack (V7.4.5)
[Impact Pack] Wildcards loading done.
Total VRAM 8192 MB, total RAM 32581 MB
pytorch version: 2.2.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
### ComfyUI Revision: 2649 [5cbaa9e0] | Released on '2024-09-05'
json_repair## OK

**Comment by Zuellni** [comment]
Follow the readme and install the appropriate wheel.
