### ISSUE TITLE
No output in Preview, No error messages

### ISSUE THREAD

**Issue by Teravus** [Zuellni/ComfyUI-ExLlama-Nodes#28]
Hey there, 

I was playing with Comfy and had a workflow that I though would benefit from expanding on a few words. 

Anyway, I installed and the nodes are "functioning", I'm just getting no output in the preview box.

In the console I see;
got prompt
Output generated in 0.12 seconds (30 context, 10 tokens, 83.33t/s)
Prompt executed in 0.13 seconds

I have tried several different models, with a variety of settings.  I recreated the workflow from scratch.  All of the models load, I see them active in CUDA.   They output nothing into the box.    There isn't a flash-attention wheel for this version of Torch+Cuda+cpython so flash_attention is false in the loader.

![image](https://github.com/user-attachments/assets/e09b3316-f163-4912-a628-169a336960f2)

Output generated in 3.43 seconds (174 context, 256 tokens, 74.64t/s)
Prompt executed in 3.43 seconds
got prompt
Output generated in 4.01 seconds (175 context, 256 tokens, 63.84t/s)
Prompt executed in 4.02 seconds
got prompt
Output generated in 1.82 seconds (178 context, 135 tokens, 74.18t/s)
Prompt executed in 1.83 seconds
got prompt
Output generated in 0.4 seconds (30 context, 10 tokens, 25.0t/s)
Prompt executed in 0.40 seconds

-------------   Startup
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-05 00:49:08.068522
** Platform: Windows
** Python version: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
** Python executable: F:\ComfyUI\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: F:\ComfyUI\ComfyUI
** Log path: F:\ComfyUI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   3.2 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 130871 MB
pytorch version: 2.5.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\ComfyUI\ComfyUI\web
bin F:\ComfyUI\ComfyUI\.venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
Total VRAM 24576 MB, total RAM 130871 MB
pytorch version: 2.5.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Initializing EasyNodes. Auto-registration: True
### ComfyUI Revision: 2859 [b4526d3f] | Released on '2024-11-24'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
ComfyUI found: F:\ComfyUI\ComfyUI
'F:\ComfyUI\ComfyUI' added to sys.path
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

Import times for custom nodes:
   0.0 seconds: F:\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXTricks
   0.0 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-MochiWrapper
   0.0 seconds: F:\ComfyUI\ComfyUI\custom_nodes\Flux-Prompt-Generator
   0.0 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Nodes
   0.1 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-to-Python-Extension
   0.2 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
   0.4 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo
   0.8 seconds: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
-----------------------

Maybe I did something stupid.  I don't know.   It says that it is outputting tokens in the terminal.   but they're not showing up in the preview. "Output generated in 4.01 seconds (175 context, 256 tokens, 63.84t/s)"

**Comment by Zuellni** [comment]
You seem to be getting output alright, so the issue likely lies with the preview node. Comfy has been changing so much on the UI side lately that I'm honestly tired of following all the developments, something could very well be broken there.

Try another text preview node for starters, iirc https://github.com/pythongosssss/ComfyUI-Custom-Scripts should have one.

**Comment by Teravus** [comment]
I can confirm that it has something to do with the preview node.    I outputted to the Print text node from custom-scripts and on the console it prints: An intric, delicate, and elegant sculpture of a silver paper clip, crafted from gleaminging metal, suspended delicatelyly from a thin wire, casting a shadow on a white background, illuminated with a soft, diffused light, creating a sense of movement and fluidity, with a hint of playfulness and whimsy.

System: 
Your job is to create visually compelling, detailed, symbolic, and perfectly composed artwork with beautiful, well-balanced color palettes. You have a deep knowledge of art history, including all past artists, known and unknown, and all art movements. You will be given an idea for a hypothetical work of art, and you will provide a creative and detailed description of the work of art in the form of a comma-separated list that begins with an improved restatement of the idea you were given, followed by details about the subject matter, visual elements, materials, techniques, and colors; you will also include adjectives that describe various qualities of the work of art. Do not use punctuation other than commas. The description should be no more than 150 words. Return only one prompt.

User: 
A silver Paperclip

Output generated in 1.13 seconds (176 context, 67 tokens, 59.29t/s)

Output:
An intric, delicate, and elegant sculpture of a silver paper clip, crafted from gleaminging metal, suspended delicatelyly from a thin wire, casting a shadow on a white background, illuminated with a soft, diffused light, creating a sense of movement and fluidity, with a hint of playfulness and whimsy.
Prompt executed in 1.13 seconds

**Comment by Zuellni** [comment]
Seems like it was a typo on my part, should work now if you update. I added printing to console for the preview node too just in case.

**Comment by Teravus** [comment]
Can confirm.   e98048093c80eb7dc240fa0ab9c0403ef7aa11d1 resolves the issue.  
![image](https://github.com/user-attachments/assets/5ee79149-f1af-4c85-b0fb-551318ea499d)

Thank You!
