### ISSUE TITLE
No module named 'exllama'

### ISSUE THREAD

**Issue by Yorha4D** [Zuellni/ComfyUI-ExLlama-Nodes#4]
`Traceback (most recent call last):
  File "D:\Blender_ComfyUI\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\__init__.py", line 1, in <module>
    from .nodes import Generator, Loader, Previewer
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\nodes.py", line 6, in <module>
    from exllama.alt_generator import ExLlamaAltGenerator
ModuleNotFoundError: No module named 'exllama'

Cannot import D:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes module for custom nodes: No module named 'exllama'`

@Zuellni

**Comment by Zuellni** [comment]
As explained in the [README](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes#installation), you have to install the ExLlama package matching your system.

**Comment by Yorha4D** [comment]
> As explained in the [README](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes#installation), you have to install the ExLlama package matching your system.如自述文件中所述，您必须安装与您的系统匹配的 ExLlama 软件包。

@Zuellni Perhaps my cuda version is too high
![image](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/116185401/fe72607a-7f74-47c0-a15c-361065b77e3a)

**Comment by Zuellni** [comment]
The package should match your `pytorch-cuda` version. You can check it with:
```
python -c "import torch; print(torch.version.cuda)"
```
If that also outputs `12.2`, you can try installing the 12.1 package but it's not guaranteed to work. There are no pre-built wheels for 12.2. You can either compile it yourself from the repository linked in the readme or downgrade your Torch.

**Comment by Yorha4D** [comment]
@Zuellni 
![image](https://github.com/Zuellni/ComfyUI-ExLlama-Nodes/assets/116185401/3053997c-6657-45b3-9f52-599d7aa6c79d)
Perhaps there are some issues with 12.2. Let me step back first. Thank you for your reply.

**Comment by Zuellni** [comment]
Make sure you're calling the same python executable ComfyUI is using. You might have to enable a venv, or conda/mamba environment before checking for CUDA and installing the package.
