### ISSUE TITLE
Error occurred after comfyui upgrade

### ISSUE THREAD

**Issue by liulsg** [Zuellni/ComfyUI-ExLlama-Nodes#6]
Error occurred when executing ZuellniExLlamaGenerator:

sample_basic(): incompatible function arguments. The following argument types are supported:
1. (arg0: torch.Tensor, arg1: float, arg2: int, arg3: float, arg4: float, arg5: float, arg6: torch.Tensor, arg7: torch.Tensor) -> None

Invoked with: tensor([[-9.0547, -8.7422, 7.3477, ..., -7.6328, -5.0000, -3.2949]]), 0.7, 20, 0.9, 0.98, 0.9980835713764517, tensor([[0]]), tensor([[0.]]), tensor([[True, True, True, ..., True, True, True]])

File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ExLlama-Nodes\nodes.py", line 96, in generate
chunk, eos, _ = model.stream()
File "D:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllamav2\generator\streaming.py", line 111, in stream
next_token, eos = self._gen_single_token(self.settings)
File "D:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllamav2\generator\streaming.py", line 204, in _gen_single_token
token, _, eos = ExLlamaV2Sampler.sample(logits, gen_settings, self.sequence_ids, random.random(), self.tokenizer, prefix_token)
File "D:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\exllamav2\generator\sampler.py", line 116, in sample
ext_c.sample_basic(logits,

**Comment by Zuellni** [comment]
What ComfyUI commit are you on now and what was the last working one for you? What's your exllamav2 package version?  
The latest commit (`ae3e4e9` as of writing this) seems to be working correctly for me.

**Comment by liulsg** [comment]
> What ComfyUI commit are you on now and what was the last working one for you? What's your exllamav2 package version? The latest commit (`ae3e4e9` as of writing this) seems to be working correctly for me.

@Zuellni  After I ran update_comfyui_and_python_dependencies, torch did not work properly after upgrading to 2.1, even though I reinstalled the support library, but I finally redownloaded comfyui portable version and reinstalled the support library. Thank you for your response.

**Comment by Zuellni** [comment]
I tried both the stable and nightly portable builds, and there appears to be an issue with exllamav2 wheels and torch 2.2 with the nightly.
```
ImportError: DLL load failed while importing exllamav2_ext: The specified procedure could not be found.
```
It might work if you compile the extension following the instructions in the exllamav2 repo but I can't do anything about this myself. Recommend using the stable release of comfyui with torch 2.1 for now.

**Comment by liulsg** [comment]
> I tried both the stable and nightly portable builds, and there appears to be an issue with exllamav2 wheels and torch 2.2 with the nightly.
> 
> ```
> ImportError: DLL load failed while importing exllamav2_ext: The specified procedure could not be found.
> ```
> 
> It might work if you compile the extension following the instructions in the exllamav2 repo but I can't do anything about this myself. Recommend using the stable release of comfyui with torch 2.1 for now.

@Zuellni ok,thanks
